name: flutter_auth
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.15.0-116.0.dev <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.4
  flutter_svg: ^1.0.3
  flutter_launcher_icons: ^0.9.2
#  flutter_icons: ^1.1.0
  firebase_core: ^1.12.0
  firebase_auth: ^3.3.8
  cloud_firestore: ^3.1.9
  modal_progress_hud_nsn: ^0.1.0-nullsafety-1
  firebase_storage: ^10.2.8
  image_picker: ^0.8.4+11
  path_provider: ^2.0.9
  path: ^1.8.0
  shared_preferences: ^2.0.13
  file_picker: ^4.3.3
dev_dependencies:
  flutter_test:
    sdk: flutter
#  flutter_launcher_name: "^0.0.1"
#
#flutter_launcher_name:
#  name: "M3lomatk"

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/finally.png"

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
